language: python
dist: xenial
sudo: required
python:
  - "3.5"
  - "3.6"
  - "3.7"
install:
  - pip install codecov
  - pip install pytest pytest-cov
  - pip install -r requirements.txt
script:
  - python -m pytest --cov=./
after_success:
- codecov
