language: python
dist: xenial
sudo: required
python:
  - "3.5"
  - "3.6"
  - "3.7"
install:
  - pip install codecov
  - pip install 'pytest>=4.6'
  - pip install 'pytest-cov==2.10.0'
  - pip install -r requirements.txt
script:
  - python -m pytest --cov=./
after_success:
- codecov
